### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by Barbaross93** [dlasagno/vscode-rasi#1]
I'm interested in trying this, but I'm not sure how to apply it. Could you explain how to install it?

**Comment by dlasagno** [comment]
I'm really glad to see your interest. This extension is basically finished, but I was too lazy to write a Readme and publish it. I may publish this on the marketplace when I get a bit of time. In the meantime, you can clone the repo and use `vsce package` to create a .vsix that you can then install with `code --install-extension file.vsix`. You can install vsce with `npm install -g vsce`.
I will update this issue when the extension will be published such that you can then install it from the marketplace and receive the updates.

**Comment by Barbaross93** [comment]
Perfect, thanks!

Just an FYI, I had to include a publisher name as well as modify the README.md before the `vsce package` command would work. Otherwise, smooth sailing after that.

Thanks for sharing this!
